{"name": "test_login_with_invalid_credentials[wrong_user-wrong_pass-Your username is invalid!]", "status": "passed", "parameters": [{"name": "username", "value": "'wrong_user'"}, {"name": "password", "value": "'wrong_pass'"}, {"name": "expected_error", "value": "'Your username is invalid!'"}], "start": 1754874662330, "stop": 1754874666022, "uuid": "71862f33-522b-4190-90d7-abf7a7b9d953", "historyId": "57bfb3687fc1837f97f6eb5e1a1cf7a5", "testCaseId": "7cc77bdf9c8f82a4c10d09af5131748e", "fullName": "tests.test_login#test_login_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "AUSYD-DT-3726"}, {"name": "thread", "value": "44896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}